### ISSUE TITLE
mmpose error

### ISSUE THREAD

**Issue by RunpeiDong** [brentyi/egoallo#13]
Hi Brent,

Excellent work! When I tried to run the hammer code on Ego4DExo data, I ran into this problem:
```sh
File "egoallo/hamer.py", line 5, in <module>
    from mmpose.apis import init_model, inference_topdown, visualize
ImportError: cannot import name 'init_model' from 'mmpose.apis' (hamer/third-party/ViTPose/mmpose/apis/__init__.py). Did you mean: 'train_model'?
```
It seems this usage of mmpose has been deprecated, can you tell me what version of mmpose do you use?

By the way, this repo is built on py3.12, while hammer is built with 3.10, there may have some environment conflicts. Do you use 3.12 and modify all packages choices to make it work on 3.12? 

Thanks,
Runpei

**Comment by RunpeiDong** [comment]
Solved, my bad.
